void borda(char m[][15]);
void base(char m[][15],Inimigo *I1,Inimigo *I2);
void renovBordas(char m[][15]);
void fase1(char m[][15]);
void fase2(char m[][15]);
void fase3(char m[][15]);
void imprimir(char m[][15]);
void andar(char m[][15],Jogador *tap,char *pa,char *diretiro);
int atirar(char m[][15],Jogador *tap,char *pa,char *diretiro,Tiro *tiro,Inimigo *I1, Inimigo *I2, int *pontos,int *contmorte);
void MovInimigoInteligente(char m[][15], Jogador *tap, Inimigo *I1, Inimigo *I2, Tiro *tiro, char *diretiroI1, char *diretiroI2,int *vidas);
void MovInimigoAleatorio(char m[][15], Jogador *tap, Inimigo *I1, Inimigo *I2, Tiro *tiro, char *diretiroI1, char *diretiroI2,int *vidas);
void tirodoInimigo1 (char m[][15], Jogador *tap, Inimigo *I1, Inimigo *I2, Tiro *tiro, char *diretiroI1, char *diretiroI2,int *vidas);
void tirodoInimigo2 (char m[][15], Jogador *tap, Inimigo *I1, Inimigo *I2, Tiro *tiro, char *diretiroI1, char *diretiroI2,int *vidas);
int RadarBase(char m[][15],Jogador *tap,Inimigo *I1,Inimigo *I2);
void limpatabuleiro(char m[][15]);
void criandofases(char m[][15]);
void vitoria(int *pontos);
void girar(char m[][15],Jogador *tap,char *diretiro,char *pa,int *pontos,int *vidas);
void printarjogadores(char m[][15]);
void andard(char m[][15],Jogador *tap,char *pa,char *diretiro);
